# ultima versione di docker-compose
version: "3.9"

services:
  frontend:
    image: "frontend"
    container_name: "frontend"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      ION_network:
        ipv4_address: 172.20.0.2
    ports:
      - "${VITE_PORT}:3001"

networks:
  ION_network:
    name: ION
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
